[all:vars]
ansible_user=ansible
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
ansible_python_interpreter=/usr/libexec/platform-python


[kube_control_plane]
master1 ansible_host=10.60.60.208 ansible_port=5522


[etcd]
master1 ansible_host=10.60.60.208 ansible_port=5522


[kube_node]
worker1 ansible_host=10.60.60.209 ansible_port=5522


[k8s_cluster:children]
kube_control_plane
kube_node
