[all:vars]
ansible_user=ansible
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
ansible_python_interpreter=/usr/libexec/platform-python


[kube_control_plane]
master1 ansible_host=10.60.60.196 ansible_port=5522
master2 ansible_host=10.60.60.197 ansible_port=5522
master3 ansible_host=10.60.60.198 ansible_port=5522


[etcd:children]
kube_control_plane


[kube_node]
worker1 ansible_host=10.60.60.199 ansible_port=5522
worker2 ansible_host=10.60.60.200 ansible_port=5522
worker3 ansible_host=10.60.60.201 ansible_port=5522
worker4 ansible_host=10.60.60.202 ansible_port=5522
worker5 ansible_host=10.60.60.203 ansible_port=5522
worker6 ansible_host=10.60.60.204 ansible_port=5522
worker7 ansible_host=10.60.60.205 ansible_port=5522


[k8s_cluster:children]
kube_control_plane
kube_node
