[all:vars]
ansible_user=ansible
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root

[kube_control_plane]
master1 ansible_host=10.60.51.195 ansible_port=5522 ansible_user=ansible
master2 ansible_host=10.60.51.196 ansible_port=5522 ansible_user=ansible
master3 ansible_host=10.60.51.197 ansible_port=5522 ansible_user=ansible

[etcd:children]
kube_control_plane

[kube_node]
worker1 ansible_host=10.60.51.198 ansible_port=5522 ansible_user=ansible
worker2 ansible_host=10.60.51.199 ansible_port=5522 ansible_user=ansible
worker3 ansible_host=10.60.51.200 ansible_port=5522 ansible_user=ansible

[k8s_cluster:children]
kube_control_plane
kube_node

